pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - NAME="fortune-whale"
      - docker build -t "$NAME" "$DRONE_BUILD_DIR"
      - docker run fortune-whale
