pipeline:

  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - NAME="hbokh/fortune-whale"
      - docker build --rm=true -t "$NAME" "$DRONE_BUILD_DIR"
      - docker run --rm hbokh/fortune-whale

  publish:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: hbokh/fortune-whale
    tag: 
      - latest
      - 0.0.2
    insecure: false
    when:
      branch: master
