pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - NAME="fortune-whale"
      - docker build --rm=true -t "$NAME" "$DRONE_BUILD_DIR"
      - docker run fortune-whale

  publish:
    docker:
      username: $$DOCKER_USERNAME
      password: $$DOCKER_PASSWORD
      email: $$DOCKER_EMAIL
      repo: hbokh/docker-drone-builder
      tag:
        - development
        - "$$BUILD_NUMBER"
      file: Dockerfile
      insecure: false
      when:
        branch: develop
